apiweb/apps/alumni/urls.py
from django.urls import path

from .views import alumnus_detail, alumnus_list

app_name = "alumni"
urlpatterns = [
    path("", view=alumnus_list, name="alumnus-list"),
    path("alumnus/<slug>/", alumnus_detail, name="alumnus-detail"),
]

apiweb/apps/survey/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from apiweb.context_processors import contactinfo

from .views import (
    survey_careerinfo_current,
    survey_careerinfo_first,
    survey_careerinfo_second,
    survey_careerinfo_third,
    survey_contactinfo,
    survey_success,
)

app_name = "survey"
urlpatterns = [
    path(
        "<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="survey/survey_reset_password.html",
            extra_context={
                "api_phonenumber_formatted": contactinfo(None)[
                    "api_phonenumber_formatted"
                ],
                "secretary_email_address": contactinfo(None)[
                    "contactinfo"
                ].secretary_email_address,
            },
            success_url=reverse_lazy("survey:contactinfo"),
            post_reset_login=True,
            post_reset_login_backend="django.contrib.auth.backends.ModelBackend",
        ),
        name="survey_url",
    ),
    path("contactinfo/", survey_contactinfo, name="contactinfo"),
    #    path(r"careerinfo/", survey_careerinfo, name="careerinfo"),
    path("careerinfo_current/", survey_careerinfo_current, name="careerinfo_current"),
    path("careerinfo_first/", survey_careerinfo_first, name="careerinfo_first"),
    path("careerinfo_second/", survey_careerinfo_second, name="careerinfo_second"),
    path("careerinfo_third/", survey_careerinfo_third, name="careerinfo_third"),
    path("thanks/", survey_success, name="survey_success"),
]

apiweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views

handler404 = "apiweb.apps.main.views.page_not_found"
handler500 = "apiweb.apps.main.views.handler500"

urlpatterns = [path("", include("apiweb.apps.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apiweb/apps/survey/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_countries.fields import CountryField

from ..alumni.models import Alumnus


class Sector(models.Model):
    name = models.CharField(max_length=200)

    date_created = models.DateTimeField(_("Date Created"), auto_now_add=True)
    date_updated = models.DateTimeField(_("Date Last Changed"), auto_now=True)
    last_updated_by = models.ForeignKey(
        get_user_model(),
        null=True,
        on_delete=models.SET_NULL,
        related_name="sectors_updated",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Job Sector"
        verbose_name_plural = "Job Sectors"


class JobAfterLeaving(models.Model):
    """Represents a job after leaving API"""

    YES_OR_NO = (
        (1, "Yes"),
        (2, "No"),
    )

    JOB_LOCATION_CHOICES = (
        (1, "NL"),
        (2, "Europe"),
        (3, "Great Bitain"),
        (4, "US"),
        (5, "Other"),
    )

    WHICH_POSITION_CHOICES = (
        (0, "Current"),
        (1, "First"),
        (2, "Second"),
        (3, "Third"),
    )

    alumnus = models.ForeignKey(Alumnus, related_name="job", on_delete=models.CASCADE)
    sector = models.ForeignKey(Sector, blank=True, null=True, on_delete=models.SET_NULL)
    company_name = models.CharField(_("Company Name"), blank=True, max_length=100)
    position_name = models.CharField(_("Position Name"), blank=True, max_length=100)
    is_inside_academia = models.PositiveSmallIntegerField(
        _("In Academia"), choices=YES_OR_NO, default=1
    )
    is_inside_astronomy = models.PositiveSmallIntegerField(
        _("In Astronomy"), choices=YES_OR_NO, null=True, blank=True
    )

    location_job = CountryField(_("Location"), blank=True)
    start_date = models.DateField(_("From"), blank=True, null=True)
    stop_date = models.DateField(_("Until"), blank=True, null=True)

    # Have 4 options for this, current, first after, second after, third after
    which_position = models.PositiveSmallIntegerField(
        _("Which position"), choices=WHICH_POSITION_CHOICES, default=0
    )

    comments = models.TextField(_("comments"), blank=True)
    last_updated_by = models.ForeignKey(
        get_user_model(),
        null=True,
        on_delete=models.SET_NULL,
        related_name="jobs_updated",
    )
    date_created = models.DateTimeField(_("Date Created"), auto_now_add=True)
    date_updated = models.DateTimeField(_("Date Last Changed"), auto_now=True)

    # Privacy
    show_job = models.BooleanField(
        _("Show job on personal page"), blank=True, default=True
    )

    class Meta:
        verbose_name = _("Job After Leaving API")
        verbose_name_plural = _("Jobs After Leaving API")

    def __str__(self):
        return self.alumnus.last_name

apiweb/apps/survey/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import SurveyCareerInfoForm, SurveyContactInfoForm
from .models import JobAfterLeaving


@login_required
def survey_contactinfo(request, use_for_main=False):
    """Step 0 of the survey is a modified password reset url/template. Once the
    Alumnus has received a personal email with a tokened url to the modified
    password reset template, pressing 'next' on that password reset form leads
    here. This form surves the purpose to gather contact information, and
    on success this form then moves on to the survey_careerinfo view/form."""
    if request.method == "POST":
        form = SurveyContactInfoForm(
            data=request.POST, instance=request.user, files=request.FILES
        )
        if form.is_valid():
            alumnus = form.save(commit=False)
            alumnus.user = request.user
            alumnus.save()
            return HttpResponseRedirect(reverse("survey:careerinfo_current"))
    else:
        form = SurveyContactInfoForm(instance=request.user)

    return render(request, "survey/survey_contactinfo.html", {"form": form})


@login_required
def survey_careerinfo_current(request):
    """Career info form is shown on success of the survey_contactinfo view/form."""
    which_position_value = 0
    try:
        prefill_instance = JobAfterLeaving.objects.all().filter(
            alumnus=request.user, which_position=which_position_value
        )[0]
    except IndexError:
        prefill_instance = False

    if request.method == "POST":
        if "finish" in request.POST:
            messages.success(
                request,
                "Thanks for taking the time to fill out our survey! Welcome to your personal alumnus page.",
            )
            return HttpResponseRedirect(
                reverse("alumni:alumnus-detail", kwargs={"slug": request.user.slug})
            )

        # TODO: this if statement is not necessary if prefill_instance is set to None in the try-expect clause above.
        if prefill_instance:
            form = SurveyCareerInfoForm(data=request.POST, instance=prefill_instance)
        else:
            form = SurveyCareerInfoForm(data=request.POST)

        if form.is_valid():
            jobafterleaving = form.save(commit=False)
            jobafterleaving.alumnus = request.user
            jobafterleaving.which_position = which_position_value
            jobafterleaving.alumnus.survey_info_updated = datetime.now()
            jobafterleaving.alumnus.save()
            print("survey, cur %s" % jobafterleaving.alumnus.survey_info_updated)
            jobafterleaving.save()
            if "next" in request.POST:
                return HttpResponseRedirect(reverse("survey:careerinfo_first"))
            elif "prev" in request.POST:
                return HttpResponseRedirect(reverse("survey:contactinfo"))
    else:
        # TODO: this if statement is not necessary if prefill_instance is set to None in the try-expect clause above.
        if prefill_instance:
            form = SurveyCareerInfoForm(instance=prefill_instance)
        else:
            form = SurveyCareerInfoForm()
    return render(request, "survey/survey_careerinfo_current.html", {"form": form})


@login_required
def survey_careerinfo_first(request):
    """Career info form is shown on success of the survey_contactinfo view/form."""
    which_position_value = 1
    try:
        prefill_instance = JobAfterLeaving.objects.all().filter(
            alumnus=request.user, which_position=which_position_value
        )[0]
    except IndexError:
        prefill_instance = False

    if request.method == "POST":
        if "finish" in request.POST:
            messages.success(
                request,
                "Thanks for taking the time to fill out our survey! Welcome to your personal alumnus page.",
            )
            return HttpResponseRedirect(
                reverse("alumni:alumnus-detail", kwargs={"slug": request.user.slug})
            )
        if prefill_instance:
            form = SurveyCareerInfoForm(data=request.POST, instance=prefill_instance)
        else:
            form = SurveyCareerInfoForm(data=request.POST)

        if form.is_valid():
            jobafterleaving = form.save(commit=False)
            jobafterleaving.alumnus = request.user
            jobafterleaving.which_position = which_position_value
            jobafterleaving.alumnus.survey_info_updated = datetime.now()
            jobafterleaving.alumnus.save()
            print("survey, 1 %s" % jobafterleaving.alumnus.survey_info_updated)
            jobafterleaving.save()
            if "next" in request.POST:
                return HttpResponseRedirect(reverse("survey:careerinfo_second"))
            elif "prev" in request.POST:
                return HttpResponseRedirect(reverse("survey:careerinfo_current"))
    else:
        if prefill_instance:
            form = SurveyCareerInfoForm(instance=prefill_instance)
        else:
            form = SurveyCareerInfoForm()
    return render(request, "survey/survey_careerinfo_first.html", {"form": form})


@login_required
def survey_careerinfo_second(request):
    """Career info form is shown on success of the survey_contactinfo view/form."""
    which_position_value = 2
    try:
        prefill_instance = JobAfterLeaving.objects.all().filter(
            alumnus=request.user, which_position=which_position_value
        )[0]
    except IndexError:
        prefill_instance = False

    if request.method == "POST":
        if "finish" in request.POST:
            messages.success(
                request,
                "Thanks for taking the time to fill out our survey! Welcome to your personal alumnus page.",
            )
            return HttpResponseRedirect(
                reverse("alumni:alumnus-detail", kwargs={"slug": request.user.slug})
            )
        if prefill_instance:
            form = SurveyCareerInfoForm(data=request.POST, instance=prefill_instance)
        else:
            form = SurveyCareerInfoForm(data=request.POST)

        if form.is_valid():
            jobafterleaving = form.save(commit=False)
            jobafterleaving.alumnus = request.user
            jobafterleaving.which_position = which_position_value
            jobafterleaving.alumnus.survey_info_updated = datetime.now()
            jobafterleaving.alumnus.save()
            print("survey, 2 %s" % jobafterleaving.alumnus.survey_info_updated)
            jobafterleaving.save()

            if "next" in request.POST:
                return HttpResponseRedirect(reverse("survey:careerinfo_third"))
            if "prev" in request.POST:
                return HttpResponseRedirect(reverse("survey:careerinfo_first"))
    else:
        if prefill_instance:
            form = SurveyCareerInfoForm(instance=prefill_instance)
        else:
            form = SurveyCareerInfoForm()
    return render(request, "survey/survey_careerinfo_second.html", {"form": form})


@login_required
def survey_careerinfo_third(request):
    """Career info form is shown on success of the survey_contactinfo view/form."""
    which_position_value = 3
    try:
        prefill_instance = JobAfterLeaving.objects.all().filter(
            alumnus=request.user, which_position=which_position_value
        )[0]
    except IndexError:
        prefill_instance = False

    if request.method == "POST":
        if prefill_instance:
            form = SurveyCareerInfoForm(data=request.POST, instance=prefill_instance)
        else:
            form = SurveyCareerInfoForm(data=request.POST)

        if form.is_valid():
            jobafterleaving = form.save(commit=False)
            jobafterleaving.alumnus = request.user
            jobafterleaving.which_position = which_position_value
            jobafterleaving.alumnus.survey_info_updated = datetime.now()
            jobafterleaving.alumnus.save()
            print("survey, 3 %s" % jobafterleaving.alumnus.survey_info_updated)
            jobafterleaving.save()
            messages.success(
                request,
                "Thanks for taking the time to fill out our survey! Welcome to your personal alumnus page.",
            )

            if "next" in request.POST:
                return HttpResponseRedirect(
                    reverse("alumni:alumnus-detail", kwargs={"slug": request.user.slug})
                )
            elif "prev" in request.POST:
                return HttpResponseRedirect(reverse("survey:careerinfo_second"))
    else:
        if prefill_instance:
            form = SurveyCareerInfoForm(instance=prefill_instance)
        else:
            form = SurveyCareerInfoForm()
    return render(request, "survey/survey_careerinfo_third.html", {"form": form})


@login_required
def survey_success(request):
    return render(request, "survey/survey_complete.html", {})

apiweb/apps/survey/templates/survey/contactinfoform.html
    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">
        <div>
            <h3>Contact Details of <a href="{% url 'alumni:alumnus-detail' request.user.slug %}" target="blank", style="color: black;">{{ request.user.full_name }}</a> <br></h3>
            <br>
            Please enter your contact information in the form below. <br>
            Except for your name, no other information is directly shown on your profile page. Within this form, however, you are given the option to make certain fields visible to the public. <br>
            Note that all of the fields are optional, thus, you can leave any number of them blank!
        </div>

        <br>

        <div class="col-xs-12">
            <form class="form-horizontal col-sm-12" role="form" action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger">
                        Please check the input in the following field(s):
                        {% for error in form.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}

                    {% if forloop.counter == 1 %}
                    <legend> Personal Information </legend>
                    {% elif forloop.counter == 14 %}
                    <legend> Contact Information </legend>
                    {% elif forloop.counter == 26 %}
                    <legend> Current Location </legend>
                    {% endif %}

                    {% if field.errors %}
                    <div class="form-group has-error has-feedback">
                    {% else %}
                    <div class="form-group">
                    {% endif %}
                        {{ field.label_tag }} {{ field }}

                        {% if field.errors %}
                        <i class="glyphicon glyphicon-remove form-control-feedback"></i>
                        <div class="alert alert-danger">
                            {% for error in field.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                        {% endif %}
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-success pull-right"> Next </button>

            </form>
        </div>

apiweb/apps/survey/templates/survey/send_survey_email.html
{% load i18n %}{% autoescape off %}Dear {{ full_name_no_title }},

The Anton Pannekoek Institute is happy to announce that we have developed and launched a new website for our alumni!
You can now search for alumni and theses of the API, starting with Anton Pannekoek up to the present day by
surfing to {{ site_name }}. You are receiving this e-mail because you are one of our alumni.

We would like to ask you to verify your (contact) information, and we kindly ask you to fill out a survey.
The goal of the survey is to gather information on your current whereabouts and occupation. Furthermore, we
intend to analyse and show (anonymised) statistics of career opportunities after leaving the API.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'survey:survey_url' uidb64=uid token=token %}
{% endblock %}
Furthermore, we have automatically created an account for you with username: {{ user.get_username }}.
You can either use that username, or this email adress as a way to log in.
In the first step of the survey we ask you to create a password, followed by providing some basic contact
information. The last part consists of questions regarding current employment.

Kind regards,

Secretariat Anton Pannekoek Institute for Astronomy
University of Amsterdam
{{ secretary_email_address }}
{{ api_phonenumber_formatted }}

P.S. In case we have mistakenly mismatched your e-mail address to one of our alumni, you can either ignore this e-mail or reply to {{ secretary_email_address }}.

{% endautoescape %}

apiweb/apps/survey/templates/survey/survey_careerinfo.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %} {{ block.super }}
<link href="/tinymce/css/" type="text/css" media="all" rel="stylesheet" />
<script>function djangoFileBrowser(field_name, url, type, win) { return false;}</script>
<script type="text/javascript" src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
{% endblock stylesheets %}

{% block title %} API - Alumni - Survey {% endblock title %}

{% block content %}

<div class="col-xs-12 main-content" role="main" style="width: 100%">
    <h1 class="text-center"> API Alumni Survey (3/3) </h1>

    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">
        <div>
            <h3> Career Information of <a href="{% url 'alumni:alumnus-detail' request.user.slug %}" target="blank", style="color: black;">{{ request.user.full_name }}</a> <br></h3>
            <br>
            Please provide us information regarding your current position.
        </div>

        <br>

        <div class="col-xs-12">
            <form class="form-horizontal col-sm-12" role="form" action="{% url 'survey:careerinfo' %}" method="post"> {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger">
                        Please check the input in the following field(s):
                        {% for error in form.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}

                    {% if forloop.counter == 1 %}
                    <legend> Current Position </legend>
                    {% endif %}

                    {% if field.errors %}
                    <div class="form-group has-error has-feedback">
                    {% else %}
                    <div class="form-group">
                    {% endif %}
                        {{ field.label_tag }} {{ field }}

                        {% if field.errors %}
                        <i class="glyphicon glyphicon-remove form-control-feedback"></i>
                        <div class="alert alert-danger">
                            {% for error in field.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                        {% endif %}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-success center-block pull-right"> Submit </button>

                </form>
        </div>
    </div>
</div>
{% endblock %}

apiweb/apps/survey/templates/survey/survey_careerinfo_current.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %} {{ block.super }}
<link href="/tinymce/css/" type="text/css" media="all" rel="stylesheet" />
<script>function djangoFileBrowser(field_name, url, type, win) { return false;}</script>
<script type="text/javascript" src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
{% endblock stylesheets %}

{% block title %} API - Alumni - Survey {% endblock title %}

{% block content %}

<div class="col-xs-12 main-content" role="main" style="width: 100%">
    <h1 class="text-center"> API Alumni Survey (3/6) </h1>

    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">
        <div>
            <h3> Career Information of <a href="{% url 'alumni:alumnus-detail' request.user.slug %}" target="blank", style="color: black;">{{ request.user.full_name }}</a> <br></h3>
            <br>
            Please provide us information regarding your <strong>current</strong> job if this job is <strong>outside the API</strong>. <br>
            <br>
            Note that all of the fields are optional, thus, you can leave any number of them blank! The provided information in this specific form will only be available for the API secretary and possible used for anonymised statistics. If you choose to show this job it will be included on your personal page. <br>
            <br>
            <h4 class="text-center"> Note: Only fill in this form if your occupation is outside the API! <br>
            If you are still an active API, please use 'Finish Survey' </h4>
        </div>

        <br>

        <div class="col-xs-12">
            <form class="form-horizontal col-sm-12" role="form" action="{% url 'survey:careerinfo_current' %}" method="post"> {% csrf_token %}

                {% if form.errors %}
                    <div class="alert alert-danger">
                        Please check the input in the following field(s):
                        {% for error in form.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}

                    {% if forloop.counter == 1 %}
                    <legend> Current Position </legend>
                    {% endif %}

                    {% if field.errors %}
                    <div class="form-group has-error has-feedback">
                    {% else %}
                    <div class="form-group">
                    {% endif %}
                        {{ field.label_tag }} {{ field }}

                        {% if field.errors %}
                        <i class="glyphicon glyphicon-remove form-control-feedback"></i>
                        <div class="alert alert-danger">
                            {% for error in field.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                        {% endif %}
                    </div>
                {% endfor %}
                <button type="submit" name="prev" class="btn btn-success center-block pull-left"> Previous</button>
                <button type="submit" name="next" class="btn btn-success center-block pull-right"> Next </button>
                <button type="submit" name="finish" class="btn btn-warning center-block pull-right"> Finish Survey </button>
                </form>
        </div>
    </div>
</div>
{% endblock %}

apiweb/apps/survey/templates/survey/survey_careerinfo_first.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %} {{ block.super }}
<link href="/tinymce/css/" type="text/css" media="all" rel="stylesheet" />
<script>function djangoFileBrowser(field_name, url, type, win) { return false;}</script>
<script type="text/javascript" src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
{% endblock stylesheets %}

{% block title %} API - Alumni - Survey {% endblock title %}

{% block content %}

<div class="col-xs-12 main-content" role="main" style="width: 100%">
    <h1 class="text-center"> API Alumni Survey (4/6) </h1>

    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">
        <div>
            <h3> Career Information of <a href="{% url 'alumni:alumnus-detail' request.user.slug %}" target="blank", style="color: black;">{{ request.user.full_name }}</a> <br></h3>
            <br>
            Please provide us information regarding your <strong>first</strong> job after leaving the API. <br>
            <br>
            Note that all of the fields are optional, thus, you can leave any number of them blank! The provided information in this specific form will only be available for the API secretary and possible used for anonymised statistics. If you choose to show this job it will be included on your personal page.
            <br>
            <h4 class="text-center"> Note: Only fill in this form if your occupation is outside the API! <br>
            If you are still an active API, please use 'Finish Survey' </h4>
        </div>

        <br>

        <div class="col-xs-12">
            <form class="form-horizontal col-sm-12" role="form" action="{% url 'survey:careerinfo_first' %}" method="post"> {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-danger">
                        Please check the input in the following field(s):
                        {% for error in form.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}

                    {% if forloop.counter == 1 %}
                    <legend> First job after leaving API </legend>
                    {% endif %}

                    {% if field.errors %}
                    <div class="form-group has-error has-feedback">
                    {% else %}
                    <div class="form-group">
                    {% endif %}
                        {{ field.label_tag }} {{ field }}

                        {% if field.errors %}
                        <i class="glyphicon glyphicon-remove form-control-feedback"></i>
                        <div class="alert alert-danger">
                            {% for error in field.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        </div>
                        {% endif %}
                        {% if field.help_text %}
                            <small class="form-text text-muted">{{ field.help_text|safe }}</small>
                        {% endif %}
                    </div>
                {% endfor %}
                <button type="submit" name="prev" class="btn btn-success pull-left"> Previous </button>
                <button type="submit" name="next" class="btn btn-success center-block pull-right"> Next </button>
                <button type="submit" name="finish" class="btn btn-warning center-block pull-right"> Finish Survey </button>

                </form>
        </div>
    </div>
</div>
{% endblock %}

apiweb/apps/survey/templates/survey/survey_complete.html
{% extends 'base.html' %}
{% load static %}

{% block title %} API - Alumni - Thanks {% endblock title %}

{% block content %}

<div class="col-xs-12 main-content" role="main" style="width: 100%">
    <h1 class="text-center"> Survey Form Successfully Submitted! </h1>

    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">
        <div>
            Dear {{ request.user.full_name }}, <br>
            <br>
            Thank you very much for taking the time to update your career and contact information in the API Alumnus Database.<br>
            <br>
            You can now <a href="{% url 'alumni:alumnus-detail' request.user.slug %}">visit your personal alumnus page. </br>
            </div>
        </div>
    </div>

</div>
{% endblock %}

apiweb/apps/survey/templates/survey/survey_contactinfo.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %} {{ block.super }}
<link href="/tinymce/css/" type="text/css" media="all" rel="stylesheet" />
<script>function djangoFileBrowser(field_name, url, type, win) { return false;}</script>
<script type="text/javascript" src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
{% endblock stylesheets %}

{% block title %} API - Alumni - Survey {% endblock title %}

{% block content %}

<div class="col-xs-12 main-content" role="main" style="width: 100%">
    <h1 class="text-center"> API Alumni Survey (2/6) </h1>

    {% include 'survey/contactinfoform.html' %}

    </div>
</div>
{% endblock %}