apiweb/apps/alumni/urls.py
from django.urls import path

from .views import alumnus_detail, alumnus_list

app_name = "alumni"
urlpatterns = [
    path("", view=alumnus_list, name="alumnus-list"),
    path("alumnus/<slug>/", alumnus_detail, name="alumnus-detail"),
]

apiweb/apps/interviews/urls.py
from django.urls import path

from . import views

app_name = "interviews"
urlpatterns = [
    path("", views.index, name="index"),
    path("<slug>", views.detail, name="detail"),
]

apiweb/apps/main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from apiweb.context_processors import contactinfo

from .views import (
    AlumnusAutocomplete,
    index,
    page_not_found,
    privacy_policy,
    redirect_to_profile,
    site_careerinfo,
    site_contactinfo,
    site_thesis_create,
    site_thesis_select,
    site_thesis_update,
)

urlpatterns = [
    path("", index, name="index"),
    path("404.html", page_not_found, name="page_not_found"),
    path("privacy-policy/", privacy_policy, name="privacy_policy"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="main/login.html",
        ),
        name="site_login",
    ),
    path("redirect_to_profile/", redirect_to_profile, name="login_success"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="main/logged_out.html"),
        name="site_logout",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="main/password_change_form.html",
            success_url=reverse_lazy("site_password_change_done"),
        ),
        name="site_password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="main/password_change_done.html",
        ),
        name="site_password_change_done",
    ),
    path("update_contactinfo/", site_contactinfo, name="site_contactinfo"),
    path(
        "update_careerinfo/<which_position_value>/",
        site_careerinfo,
        name="site_careerinfo",
    ),
    path("select_thesis/", site_thesis_select, name="site_thesis_select"),
    path("update_thesis/<slug>", site_thesis_update, name="site_thesis_update"),
    path(
        "alumnus-autocomplete/",
        AlumnusAutocomplete.as_view(),
        name="alumnus-autocomplete",
    ),
    path("create_thesis/", site_thesis_create, name="site_thesis_create"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="main/password_reset_form.html",
            extra_context={
                "api_phonenumber_formatted": contactinfo(None)[
                    "api_phonenumber_formatted"
                ],
                "secretary_email_address": contactinfo(None)[
                    "contactinfo"
                ].secretary_email_address,
            },
            email_template_name="main/password_reset_email.html",
            extra_email_context={
                "api_phonenumber_formatted": contactinfo(None)[
                    "api_phonenumber_formatted"
                ],
                "secretary_email_address": contactinfo(None)[
                    "contactinfo"
                ].secretary_email_address,
            },
            success_url=reverse_lazy("site_password_reset_done"),
        ),
        name="site_password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="main/password_reset_done.html",
            extra_context={
                "api_phonenumber_formatted": contactinfo(None)[
                    "api_phonenumber_formatted"
                ],
                "secretary_email_address": contactinfo(None)[
                    "contactinfo"
                ].secretary_email_address,
            },
        ),
        name="site_password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="main/password_reset_confirm.html",
            success_url=reverse_lazy("site_password_reset_complete"),
        ),
        name="site_password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="main/password_reset_complete.html"
        ),
        name="site_password_reset_complete",
    ),
]

apiweb/apps/research/urls.py
from django.urls import path

from .views import thesis_detail, thesis_has_no_pdf, thesis_list

app_name = "research"
urlpatterns = [
    path("", view=thesis_list, name="thesis-list"),
    path("<slug>", thesis_detail, name="thesis-detail"),
    path("thesis_not_found", thesis_has_no_pdf, name="thesis-has-no-pdf"),
]

apiweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views

handler404 = "apiweb.apps.main.views.page_not_found"
handler500 = "apiweb.apps.main.views.handler500"

urlpatterns = [path("", include("apiweb.apps.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apiweb/apps/main/models.py
import os.path

from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _
from tinymce.models import HTMLField


def place_welcome_photo(instance, filename):
    return os.path.join("uploads", filename)


def validate_only_one_instance(obj):
    """Allow only one instance of a model to be created, in this case WelcomeMessage and ContactInfo"""
    model = obj.__class__
    if model.objects.count() > 0 and obj.id != model.objects.get().id:
        raise ValidationError(
            "Errror: only 1 instance of {0} is allowed and it already exists.".format(
                model.__name__
            )
        )


class WelcomeMessage(models.Model):
    text = HTMLField(verbose_name=_("Welcome Text"), blank=True, default="Lorum Ipsum")
    photo = models.ImageField(
        _("Welcome Photo"), upload_to=place_welcome_photo, blank=True, null=True
    )

    class Meta:
        verbose_name = _("Welcome Page")
        verbose_name_plural = _("Welcome Page")

    def clean(self):
        validate_only_one_instance(self)


class PrivacyPolicy(models.Model):
    policy = HTMLField(verbose_name=_("Privacy Policy"), blank=True)
    last_updated = models.DateTimeField(_("Last Updated"), auto_now=True)

    class Meta:
        verbose_name = _("Privacy Policy")
        verbose_name_plural = _("Privacy Policy")

    def clean(self):
        validate_only_one_instance(self)


class ContactInfo(models.Model):
    secretary_email_address = models.EmailField(
        _("API Secretariat e-mail address"), default="secr-astro-science@uva.nl"
    )
    address_api = models.CharField(
        _("API Address"), max_length=256, default="Sciencepark 904, 1098XH, Amsterdam"
    )
    postbox_address_api = models.CharField(
        _("API PO Box Address"),
        max_length=256,
        default="PO Box 94249, 1090 GE Amsterdam",
    )
    telephone_api = models.CharField(
        _("API Phone Number"), default="0031205257491", max_length=20
    )
    webmaster_email_address = models.EmailField(
        _("API Webmaster e-mail address"), default="secr-astro-science@uva.nl"
    )

    class Meta:
        verbose_name = "API Contact Info"
        verbose_name_plural = "API Contact Info"

    def clean(self):
        validate_only_one_instance(self)

apiweb/apps/alumni/forms.py
import copy

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.forms.utils import ErrorList
from django.utils.translation import ugettext_lazy as _
from tinymce.widgets import TinyMCE

from ...settings import TINYMCE_MINIMAL_CONFIG
from .models import Alumnus, PreviousPosition


class PreviousPositionAdminForm(forms.ModelForm):
    nova = forms.MultipleChoiceField(
        widget=forms.RadioSelect(), choices=PreviousPosition.NOVA_NETWORK
    )
    # Remove following line for dropdown.
    funding = forms.MultipleChoiceField(
        widget=forms.RadioSelect(), choices=PreviousPosition.FUNDING
    )


class AlumnusAdminForm(UserChangeForm):
    # Change biography to TinyMCE field
    look = copy.copy(TINYMCE_MINIMAL_CONFIG)
    look["width"] = ""
    look["height"] = "200"
    biography = forms.CharField(required=False, widget=TinyMCE(mce_attrs=look))

    class Meta:
        fields = "__all__"
        model = Alumnus

    username = forms.CharField(
        required=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and ./+/-/_ only."
        ),
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    email = forms.EmailField(
        required=False,
        help_text="Your email address will also serve as a way to log in",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    def clean(self):
        super().clean()
        username = self.cleaned_data.get("username")
        if "@" in username:
            self._errors["username"] = ErrorList()
            self._errors["username"].append("The username cannot contain '@'.")

        initials = self.cleaned_data.get("initials")
        if any(str.isdigit(c) for c in initials):
            self._errors["initials"] = ErrorList()
            self._errors["initials"].append("Initials cannot contain numbers")
        if "." in initials:
            self._errors["initials"] = ErrorList()
            self._errors["initials"].append(
                "Please give initials without dots, letters only"
            )

        first_name = self.cleaned_data.get("first_name")
        if any(str.isdigit(c) for c in first_name):
            self._errors["first_name"] = ErrorList()
            self._errors["first_name"].append("First names cannot contain numbers")

        prefix = self.cleaned_data.get("prefix")
        if any(str.isdigit(c) for c in prefix):
            self._errors["prefix"] = ErrorList()
            self._errors["prefix"].append("Prefixes cannot contain numbers")

        # As last name is already required, we cannot just override this stuff. So lets' ''try''
        last_name = self.cleaned_data.get("last_name")
        if last_name and any(str.isdigit(c) for c in last_name):
            self._errors["last_name"] = ErrorList()
            self._errors["last_name"].append("Last names cannot contain numbers")

        place_of_birth = self.cleaned_data.get("place_of_birth")
        if any(str.isdigit(c) for c in place_of_birth):
            self._errors["place_of_birth"] = ErrorList()
            self._errors["place_of_birth"].append(
                "Places of birth cannot contain numbers"
            )

        mobile = self.cleaned_data.get("mobile")
        if mobile and not any(str.isdigit(c) for c in mobile):
            self._errors["mobile"] = ErrorList()
            self._errors["mobile"].append("Phone numbers can only contain numbers")

        home_phone = self.cleaned_data.get("home_phone")
        if home_phone and not any(str.isdigit(c) for c in home_phone):
            self._errors["home_phone"] = ErrorList()
            self._errors["home_phone"].append("Phone numbers can only contain numbers")

        work_phone = self.cleaned_data.get("work_phone")
        if work_phone and not any(str.isdigit(c) for c in work_phone):
            self._errors["work_phone"] = ErrorList()
            self._errors["work_phone"].append("Phone numbers can only contain numbers")

        # Because there is also a possibility to log in with email, one must not
        # use an email which is already in use.
        # TODO: if the user has an email, but the form is empty, that means that
        # the person wants to remove the data, but this way wouldt let it
        # SO make a check whether there is instance data but form data is empty

        email = self.cleaned_data.get("email")
        if email:

            # Remove this instance object from duplicate emails object list
            duplicate_emails_excluded = Alumnus.objects.filter(email=email).exclude(
                pk=self.instance.pk
            )
            # TODO: Change len() to .count()
            if len(duplicate_emails_excluded) > 0:
                self.errors["email"] = ErrorList()
                self.errors["email"].append("The chosen email address is already used")


# ##NEW USERFORM TEST
UserModel = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ("username", "email")

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs.update(
                {"autofocus": True}
            )

    def clean_email(self):
        super().clean()
        email = self.cleaned_data.get("email")
        duplicate_emails = Alumnus.objects.filter(email=email)
        if len(duplicate_emails) > 0:
            self.errors["email"] = ErrorList()
            self.errors["email"].append("The chosen email address is already used")
        return email

apiweb/apps/main/forms.py
from dal import autocomplete
from django import forms

from ..alumni.templatetags.template_filters import display_thesis_type
from ..research.models import Thesis


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "class": "form-control required",
                "placeholder": "What is your name?",
            }
        ),
    )
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={
                "class": "form-control required",
                "placeholder": "What would you like to tell us?",
            }
        ),
    )
    sender = forms.EmailField(
        required=False,
        widget=forms.EmailInput(
            attrs={
                "class": "form-control email",
                "placeholder": "email@adres.nl - so we know how to reach you",
            }
        ),
    )
    cc_myself = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={"class": "checkchoice"})
    )


class SelectThesisForm(forms.Form):
    def __init__(self, alumnus, *args, **kwargs):
        super(SelectThesisForm, self).__init__(*args, **kwargs)

        # Only show theses of the relevant Alumnus in the queryset
        self.fields["which_thesis"].queryset = Thesis.objects.filter(alumnus=alumnus)
        # Add the type to the choices, to make it more clear.
        self.fields["which_thesis"].label_from_instance = lambda obj: "%s: %s" % (
            display_thesis_type(obj.type),
            obj.title,
        )

    which_thesis = forms.ModelChoiceField(
        label="Which thesis do you want to change?",
        required=False,
        queryset=None,  # note that we set the queryset in the init method above
        widget=forms.Select(attrs={"class": "form-control"}),
    )


class ThesisForm(forms.ModelForm):
    class Meta:
        model = Thesis
        fields = (
            "type",
            "date_start",
            "date_start",
            "date_stop",
            "title",
            "date_of_defence",
            "url",
            "pdf",
            "photo",
            "advisor",
        )

        widgets = {
            "type": forms.Select(attrs={"class": "form-control"}),
            "date_start": forms.DateInput(attrs={"class": "form-control"}),
            "date_stop": forms.DateInput(attrs={"class": "form-control"}),
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "date_of_defence": forms.DateInput(attrs={"class": "form-control"}),
            "url": forms.URLInput(attrs={"class": "form-control"}),
            "advisor": autocomplete.ModelSelect2Multiple(
                url="alumnus-autocomplete", attrs={"class": "form-control"}
            )
            # use FileInput to remove the clear tickbox
            # "pdf": forms.ClearableFileInput(),
            # "photo": forms.ClearableFileInput(),
        }

apiweb/apps/main/templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %} API - Alumni - Contact {% endblock title %}

{% block content %}

<div class="main-content" role="main" >
    <h1 class="text-center"> Contact </h1>

    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">
        <div>
            Are you an API alumnus? We would love to hear from you!

            You can let us know about any updates or changes to your
            information via this contact form or by
            <a href="mailto:{{ contactinfo.secretary_email_address}}">email</a>
            , or just let us know how you’re doing! We also welcome any
            questions, feedback or suggestions.
        </div>

        <br>

        <div class="col-xs-12">
            <form class="form-horizontal" role="form" action="." method="post"> {% csrf_token %}
                {{ form.non_field_errors }}

                <div class="form-group">
                    <label>Name</label>
                    {{ form.name }}
                    <i>{{ form.name.errors }}</i>
                </div>

                <div class="form-group">
                    <label>Message</label>

                    {{ form.message }}
                    <i>{{ form.message.errors|escape }}</i>
                </div>

                <div class="form-group">
                    {{ form.sender.errors }}

                    <label>Email</label>
                    {{ form.sender }}
                </div>

                <div class="form-group">
                    {{ form.cc_myself.errors }}

                    {{ form.cc_myself }}
                    <label>Send a copy to yourself</label>
                    <div class="form-group"><button type="submit" class="btn btn-success center-block"> Send </button> <p class="help-block pull-left text-danger hide" id="form-error">&nbsp; The form is not valid. </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apiweb/apps/main/templates/main/contactinfo_change_form.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %} {{ block.super }}
<link href="/tinymce/css/" type="text/css" media="all" rel="stylesheet" />
<script>function djangoFileBrowser(field_name, url, type, win) { return false;}</script>
<script type="text/javascript" src="{% static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
{% endblock stylesheets %}

{% block title %} API - Alumni - Contactinfo {% endblock title %}

{% block content %}

<div class="col-xs-12 main-content" role="main" style="width: 100%">
    <h1 class="text-center"> Updating <strong>Contactinfo</strong> </h1>

    {% include 'survey/contactinfoform.html' %}

    </div>
</div>
{% endblock %}

apiweb/apps/main/templates/main/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} API - Welcome {% endblock title %}
{# TODO: remove css/frontpage.css, but it is left to show how to load additional per-page css #}
{% block stylesheets %} {{ block.super }} <link rel="stylesheet" type="text/css" href="{#% static 'css/frontpage.css' %#}" />{% endblock stylesheets %}


{% block content %}
<div class="main-content" role="main">

    <div class="col-xs-12 col-lg-8 pull-right text-justify">
        <h2 class="text-left">Anton Pannekoek Institute | Alumni </h2>
        {% autoescape off %}
        {{ welcome_text }}
        {% endautoescape %}
    </div>

    <div class="col-xs-12 col-lg-4 pull-left text-justify">
        {% if latest_post %}
        <table class="table">
            <thead><tr><th style="padding-top: 0px; padding-bottom: 0px;"><h2 class="text-left" style="margin-bottom: 0px;"> Latest Interview </h2></tr></th></thead>
            <tbody><tr><td style="padding-top: 0px; padding-bottom: 0px;">
                {% if request.user.is_authenticated %}
                <h5 class="text-left">{{ latest_post.date_published|date:"M d, Y"}} • <a href="{% url 'alumni:alumnus-detail' latest_post.alumnus.slug %}">{{ latest_post.alumnus.full_name }}</a></h5>
                {% autoescape off %}
                {{ latest_post.teaser }}
                <a href="{% url 'interviews:detail' latest_post.slug %}">
                    <button class="btn btn-primary pull-right" type="submit">Read More</button></a>
                {% endautoescape %}
                {% else %}
                <h5 class="text-left"><a href="{% url 'site_login' %}">Please login to view this content.</a></h5>
                {% endif %}
            </td></tr></tbody>
        </table>
        {% endif %}

        <table class="table">
            <thead>
                <tr><th style="padding-top: 0px; padding-bottom: 0px;">
                        <h2 class="text-left" style="margin-top: 0px; margin-bottom: 0px;"> Recent Theses </h2>
                </tr></th>
            </thead>
            <tbody>
            <tr><td style="padding-top: 0px; padding-bottom: 0px;">
                {% if request.user.is_authenticated %}
                    <h5 class="text-left">
                        {{ latest_thesis.date_of_defence|date:"M d, Y" }} • <a href="{% url 'alumni:alumnus-detail' latest_thesis.alumnus.slug %}">{{ latest_thesis.author }}</a>
                    </h5>
                    <a href="{% url 'research:thesis-detail' latest_thesis.slug %}">{{ latest_thesis.title }}</a>
                    {% else %}
                    <h5 class="text-left"><a href="{% url 'site_login' %}">Please login to view this content.</a></h5
                    {% endif %}

            </td></tr>
            </tbody>
        </table>
    </div>
    <div class="col-xs-12" style="margin-top: 50px; margin-bottom: 50px;">
        <img src="media/uploads/API_Alumni_Groupphoto.png" class="img-responsive"></img>
    </div>
</div>
{% endblock %}

apiweb/apps/main/templates/main/login.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}{{ block.super }} {% endblock %}

{% block title %} API - Alumni - Login {% endblock title %}

{% block content %}

<div class="main-content" role="main" >

    <h1 class="text-center"> API Alumni Login </h1>

    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">
        {% if form.errors %}
        <div class="alert alert-danger">
            Invalid Username (or email)/Password. Please try again.
        </div>
        {% endif %}

        <form class="form-horizontal col-sm-12" role="form" action="" method="post"> {% csrf_token %}
            {% if form.errors %}
            <div class="form-group has-error has-feedback">
            {% else %}
            <div class="form-group">
            {% endif %}
                <label for="id_username">Username/Email:</label>
                <input class="form-control" type="text" name="username" required="" id="id_username">
                {% if form.errors %}
                    <i class="glyphicon glyphicon-remove form-control-feedback"></i>
                {% endif %}
            </div>

            {% if form.errors %}
            <div class="form-group has-error has-feedback">
            {% else %}
            <div class="form-group">
            {% endif %}
                <label for="id_password">Password:</label>
                <input class="form-control" type="password" name="password" required="" id="id_password">
                {% if form.errors %}
                    <i class="glyphicon glyphicon-remove form-control-feedback"></i>
                {% endif %}
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-success center-block"> Log In </button>
            </div>

            <div class="text-center">
                {% url 'site_password_reset' as password_reset_url %}
                {% if password_reset_url %}
                    <a href="{{ password_reset_url }}">
                        Forgotten your password or username?
                    </a>
                {% endif %}

            </div>
        </form>
    </form>

</div>
{% endblock %}

apiweb/apps/main/templates/main/password_change_done.html
{% extends "base.html" %}

{% block content %}

<div class="main-content" role="main">

    <h1 class="text-center"> Resetting Password: Done </h1>

    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">
        <p> Your password was changed. </p>
    </div>
</div>

{% endblock %}

apiweb/apps/main/templates/main/password_change_form.html
{% extends "base.html" %}
{% load static %}

{% block title %} API - Alumni - Password Change {% endblock title %}

{% block content %}
<div class="main-content" role="main">
    <h1 class="text-center"> API Alumni Password Change </h1>
    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">

        <div>
            Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly.
        </div>

        <br>

        <div class="col-xs-12">
            <form class="form-horizontal" method="post">{% csrf_token %}
                {% if form.old_password.errors %}
                <div class="form-group has-error has-feedback">
                {% else %}
                <div class="form-group">
                {% endif %}
                    <label for="id_old_password">Old password:</label>
                    <input class="form-control" type="password" name="old_password" autofocus required id="id_old_password"/>
                    {% if form.old_password.errors %}
                    <i class="glyphicon glyphicon-remove form-control-feedback"></i>
                    <div class="alert alert-danger">
                        {% for error in form.old_password.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>

                {% if form.new_password1.errors %}
                <div class="form-group has-error has-feedback">
                {% else %}
                <div class="form-group">
                {% endif %}
                    <label for="id_new_password1">New password:</label>
                    <input class="form-control"  type="password" name="new_password1" required id="id_new_password1"/>
                    {% if form.new_password1.errors %}
                    <i class="glyphicon glyphicon-remove form-control-feedback"></i>
                    <div class="alert alert-danger">
                        {% for error in form.new_password1.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% if form.new_password1.help_text %}
                    <div class="help">{{ form.new_password1.help_text|safe }}</div>
                    {% endif %}
                </div>

                {% if form.new_password2.errors %}
                <div class="form-group has-error has-feedback">
                {% else %}
                <div class="form-group">
                {% endif %}
                    <label for="id_new_password2">New password confirmation:</label>
                    <input class="form-control" type="password" name="new_password2" required id="id_new_password2"/>
                    {% if form.new_password2.errors %}
                    <i class="glyphicon glyphicon-remove form-control-feedback"></i>
                    <div class="alert alert-danger">
                        {% for error in form.new_password2.errors %}
                            {{ error|escape }}
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success center-block">Change my password</button>
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock %}

apiweb/apps/main/templates/main/password_reset_complete.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %} {{ block.super }} {% endblock %}

{% block title %} API - Alumni - Password Reset {% endblock title %}

{% block content %}
<div class="main-content" role="main">

    <h1 class="text-center"> API Alumni Password Reset > Done </h1>

    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">

        <p>Your password has been set.  You may go ahead and log in now.</p>

        <p><a href="{% url 'site_login' %}">Log in</a></p>

    </div>
</div>
{% endblock %}

apiweb/apps/main/templates/main/password_reset_form.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %} {{ block.super }} {% endblock %}

{% block title %} API - Alumni - Password Reset {% endblock title %}

{% block content %}
<div class="main-content" role="main">

    <h1 class="text-center"> API Alumni Password Reset </h1>

    <div id="contact-form-wrapper" class="text-justify col-xs-12 col-sm-8 col-sm-offset-2 ">

        <form method="post">{% csrf_token %}
            <div class="form-group">
                Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one. <br>
            </div>

            <div class="form-group">
                {{ form.email.errors }}
                <label for="id_email"> Email address: </label>
                <input class="form-control" type="email" name="email" maxlength="254" required="" id="id_email">
            </div>

            <div class="form-group">
                If you are uncertain which one of your email addresses we have in our database, you can look at your personal
                page. If you cannot find the email address, please
                contact us via email at <a href="mailto:{{ secretary_email_address }}">{{ secretary_email_address }}</a>,
                or call us at <a href="tel:{{ api_phonenumber_formatted }}">{{ api_phonenumber_formatted }}</a>.
            </div>

            <button type="submit" class="btn btn-danger center-block"> Send Password Reset Email </button>
        </form>

    </div>
</div>
{% endblock %}