apiweb/apps/alumni/urls.py
from django.urls import path

from .views import alumnus_detail, alumnus_list

app_name = "alumni"
urlpatterns = [
    path("", view=alumnus_list, name="alumnus-list"),
    path("alumnus/<slug>/", alumnus_detail, name="alumnus-detail"),
]

apiweb/apps/interviews/urls.py
from django.urls import path

from . import views

app_name = "interviews"
urlpatterns = [
    path("", views.index, name="index"),
    path("<slug>", views.detail, name="detail"),
]

apiweb/apps/main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from apiweb.context_processors import contactinfo

from .views import (
    AlumnusAutocomplete,
    index,
    page_not_found,
    privacy_policy,
    redirect_to_profile,
    site_careerinfo,
    site_contactinfo,
    site_thesis_create,
    site_thesis_select,
    site_thesis_update,
)

urlpatterns = [
    path("", index, name="index"),
    path("404.html", page_not_found, name="page_not_found"),
    path("privacy-policy/", privacy_policy, name="privacy_policy"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="main/login.html",
        ),
        name="site_login",
    ),
    path("redirect_to_profile/", redirect_to_profile, name="login_success"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="main/logged_out.html"),
        name="site_logout",
    ),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="main/password_change_form.html",
            success_url=reverse_lazy("site_password_change_done"),
        ),
        name="site_password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="main/password_change_done.html",
        ),
        name="site_password_change_done",
    ),
    path("update_contactinfo/", site_contactinfo, name="site_contactinfo"),
    path(
        "update_careerinfo/<which_position_value>/",
        site_careerinfo,
        name="site_careerinfo",
    ),
    path("select_thesis/", site_thesis_select, name="site_thesis_select"),
    path("update_thesis/<slug>", site_thesis_update, name="site_thesis_update"),
    path(
        "alumnus-autocomplete/",
        AlumnusAutocomplete.as_view(),
        name="alumnus-autocomplete",
    ),
    path("create_thesis/", site_thesis_create, name="site_thesis_create"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="main/password_reset_form.html",
            extra_context={
                "api_phonenumber_formatted": contactinfo(None)[
                    "api_phonenumber_formatted"
                ],
                "secretary_email_address": contactinfo(None)[
                    "contactinfo"
                ].secretary_email_address,
            },
            email_template_name="main/password_reset_email.html",
            extra_email_context={
                "api_phonenumber_formatted": contactinfo(None)[
                    "api_phonenumber_formatted"
                ],
                "secretary_email_address": contactinfo(None)[
                    "contactinfo"
                ].secretary_email_address,
            },
            success_url=reverse_lazy("site_password_reset_done"),
        ),
        name="site_password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="main/password_reset_done.html",
            extra_context={
                "api_phonenumber_formatted": contactinfo(None)[
                    "api_phonenumber_formatted"
                ],
                "secretary_email_address": contactinfo(None)[
                    "contactinfo"
                ].secretary_email_address,
            },
        ),
        name="site_password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="main/password_reset_confirm.html",
            success_url=reverse_lazy("site_password_reset_complete"),
        ),
        name="site_password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="main/password_reset_complete.html"
        ),
        name="site_password_reset_complete",
    ),
]

apiweb/apps/research/urls.py
from django.urls import path

from .views import thesis_detail, thesis_has_no_pdf, thesis_list

app_name = "research"
urlpatterns = [
    path("", view=thesis_list, name="thesis-list"),
    path("<slug>", thesis_detail, name="thesis-detail"),
    path("thesis_not_found", thesis_has_no_pdf, name="thesis-has-no-pdf"),
]

apiweb/apps/urls.py
from ajax_select import urls as ajax_select_urls
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from filebrowser.sites import site

from apiweb.context_processors import contactinfo

admin.autodiscover()

handler404 = "apiweb.apps.main.views.page_not_found"
handler500 = "apiweb.apps.main.views.handler500"


def trigger_error(request):
    division_by_zero = 1 / 0  # noqa F841


urlpatterns = [
    path("sentry-debug/", trigger_error),
    path("admin/filebrowser/", site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("ajax_select/", include(ajax_select_urls)),
    path("admin/", admin.site.urls),
    path(
        "admin/password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html",
            extra_context={
                "api_phonenumber_formatted": contactinfo(None)[
                    "api_phonenumber_formatted"
                ],
                "secretary_email_address": contactinfo(None)[
                    "contactinfo"
                ].secretary_email_address,
            },
            email_template_name="registration/password_reset_email.html",
            extra_email_context={
                "api_phonenumber_formatted": contactinfo(None)[
                    "api_phonenumber_formatted"
                ],
                "secretary_email_address": contactinfo(None)[
                    "contactinfo"
                ].secretary_email_address,
            },
        ),
        name="password_reset",
    ),
    path("admin/", include("django.contrib.auth.urls")),
    path("alumni/", include("apiweb.apps.alumni.urls")),
    path("theses/", include("apiweb.apps.research.urls")),
    path("interviews/", include("apiweb.apps.interviews.urls")),
    path("search/", include("apiweb.apps.search.urls")),
    path("survey/", include("apiweb.apps.survey.urls")),
    path("visualization/", include("apiweb.apps.visualization.urls")),
    path("", include("apiweb.apps.main.urls")),
]

apiweb/apps/visualization/urls.py
from django.urls import path

from .views import tree, view_a, view_b, view_d, view_e, view_f

app_name = "visualization"
urlpatterns = [
    path("student_supervisor_tree", view=tree, name="tree"),
    path("in_astronomy", view=view_a, name="view_a"),
    path("job_location", view=view_b, name="view_b"),
    path("job_sector", view=view_d, name="view_d"),
    path("land_of_origin", view=view_e, name="view_e"),
    path("alumni_gender", view=view_f, name="view_f"),
]

apiweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views

handler404 = "apiweb.apps.main.views.page_not_found"
handler500 = "apiweb.apps.main.views.handler500"

urlpatterns = [path("", include("apiweb.apps.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apiweb/apps/alumni/views.py
from django import template
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, render

from .models import Alumnus

register = template.Library()


@login_required
def alumnus_list(request):
    alumni = Alumnus.objects.all()

    # Get filters
    defence_year = request.GET.getlist("year", None)
    degree_type = request.GET.getlist("type", None)
    sort_on = request.GET.getlist("sort", None)

    # Apply filters
    # TODO: if filtered/sorted on postdoc, then the year range is not limited to postdoc
    # so also alumni with PhD/MSc in the year range are shown
    if defence_year:
        multifilter = Q()
        for year in defence_year:
            end_year = str(int(year) + 10)
            if year == "1900":
                end_year = str(int(year) + 50)
            date_range = [year + "-01-01", end_year + "-01-01"]
            multifilter = multifilter | Q(theses__date_of_defence__range=date_range)
            multifilter = multifilter | Q(positions__date_stop__range=date_range)
            multifilter = multifilter | Q(positions__date_start__range=date_range)
            multifilter = multifilter | Q(positions__date_stop__range=date_range)
            # multifilter = multifilter

            # print(Q(positions__date_stop__range=date_range))
            # print(Q(positions__date_start__range=date_range))
            # print(Q(positions__date_end__range=date_range))

        alumni = alumni.filter(multifilter).distinct()

    if degree_type:
        multifilter = Q()
        for degree in degree_type:
            multifilter = multifilter | Q(theses__type=degree)

        alumni = alumni.filter(multifilter).distinct()

    # Sort the list
    if sort_on:
        if sort_on[0] == "alumnus_az":
            alumni = alumni.order_by("last_name")
        if sort_on[0] == "alumnus_za":
            alumni = alumni.order_by("-last_name")

        # Caution: sorting on degree/position implies filtering also
        if sort_on[0] == "msc_lh":
            alumni = (
                alumni.filter(theses__type__iexact="msc")
                .distinct()
                .order_by("theses__date_of_defence")
            )

        if sort_on[0] == "msc_hl":
            alumni = (
                alumni.filter(theses__type__iexact="msc")
                .distinct()
                .order_by("-theses__date_of_defence")
            )

        if sort_on[0] == "phd_lh":
            alumni = (
                alumni.filter(theses__type__iexact="phd")
                .distinct()
                .order_by("theses__date_of_defence")
            )
        if sort_on[0] == "phd_hl":
            alumni = (
                alumni.filter(theses__type__iexact="phd")
                .distinct()
                .order_by("-theses__date_of_defence")
            )

        if sort_on[0] == "pd_lh":
            alumni = (
                alumni.filter(positions__type__name__in=["Postdoc"])
                .distinct()
                .order_by("positions__date_stop")
            )

        if sort_on[0] == "pd_hl":
            alumni = (
                alumni.filter(positions__type__name__in=["Postdoc"])
                .distinct()
                .order_by("positions__date_start")
            )

        # TODO: if an alumnus has several staff positions, then the latest date_stop must be returned.
        # Is this aggregating / grouping several tables together, then taking the max?
        if sort_on[0] == "staff_lh":
            alumni = (
                alumni.filter(
                    positions__type__name__in=[
                        "Full Professor",
                        "Research Staff",
                        "Adjunct Staff",
                        "Faculty Staff",
                    ]
                )
                .distinct()
                .order_by("positions__date_stop")
            )
        if sort_on[0] == "staff_hl":
            alumni = (
                alumni.filter(
                    positions__type__name__in=[
                        "Full Professor",
                        "Research Staff",
                        "Adjunct Staff",
                        "Faculty Staff",
                    ]
                )
                .distinct()
                .order_by("positions__date_start")
            )

        # if sort_on[0] == "staff_hl":
        #     alumni = alumni.filter(positions__type__name__in=["Full Professor", "Research Staff",
        #         "Adjunct Staff", "Faculty Staff"]).distinct().order_by("-positions__date_stop")

        if sort_on[0] == "obp_lh":
            alumni = (
                alumni.filter(
                    positions__type__name__in=[
                        "Instrumentation",
                        "Institute Manager",
                        "Outreach",
                        "OBP",
                        "Software Developer",
                        "Nova",
                    ]
                )
                .distinct()
                .order_by("positions__date_stop")
            )

        if sort_on[0] == "obp_hl":
            alumni = (
                alumni.filter(
                    positions__type__name__in=[
                        "Instrumentation",
                        "Institute Manager",
                        "Outreach",
                        "OBP",
                        "Software Developer",
                        "Nova",
                    ]
                )
                .distinct()
                .order_by("positions__date_start")
            )

        # if sort_on[0] == "obp_hl":
        #     alumni = alumni.filter(positions__type__name__in=["Instrumentation", "Institute Manager",
        #         "Outreach", "OBP", "Software Developer", "Nova" ]).distinct().order_by("-positions__date_stop")
    else:
        alumni = alumni.order_by("last_name")

    # TODO: only show unique results, though distinct on columns is not supported by sqlite3
    # alumni=alumni.distinct("last_name")
    # FIX: use python to uniqueify
    alumnus_unique = []
    for alumnus in alumni:
        if alumnus not in alumnus_unique:
            alumnus_unique.append(alumnus)
    alumni = alumnus_unique[:]

    # Paginate the list
    alumni_per_page = request.GET.get("limit", 15)

    try:
        alumni_per_page = int(alumni_per_page)
    except ValueError as ScriptKiddyHackings:
        if "invalid literal for int() with base 10:" in str(ScriptKiddyHackings):
            msg = "Error: '{0}' is not a valid limit, please use a number.".format(
                alumni_per_page
            )
            messages.error(request, msg)
            alumni_per_page = 15
        else:
            raise Http404

    if alumni_per_page < 15:
        msg = "Error: '{0}' is not a valid limit, please use a number above 15.".format(
            alumni_per_page
        )
        alumni_per_page = 15
        messages.error(request, msg)
    if alumni_per_page > 200:
        msg = (
            "Error: '{0}' is not a valid limit, please use a number below 200.".format(
                alumni_per_page
            )
        )
        messages.error(request, msg)
        alumni_per_page = 200

    paginator = Paginator(alumni, alumni_per_page)
    page = request.GET.get("page", 1)

    try:
        page = int(page)
    except ValueError as ScriptKiddyHackings:
        if "invalid literal for int() with base 10:" in str(ScriptKiddyHackings):
            msg = "Error: '{0}' is not a valid pagenumber, please use a number.".format(
                page
            )
            messages.error(request, msg)
            page = 1
        else:
            raise Http404

    try:
        alumni = paginator.page(page)
    except PageNotAnInteger:
        msg = "Error: '{0}' is not a valid pagenumber.".format(page)
        messages.error(request, msg)
        alumni = paginator.page(1)
    except EmptyPage:
        msg = "Error: '{0}' is not a valid pagenumber.".format(page)
        messages.error(request, msg)
        alumni = paginator.page(paginator.num_pages)

    return render(
        request,
        "alumni/alumnus_list.html",
        {"alumni": alumni, "alumni_per_page": int(alumni_per_page)},
    )


@login_required
def alumnus_detail(request, slug):
    alumnus = get_object_or_404(Alumnus, slug=slug)
    return render(request, "alumni/alumnus_detail.html", {"alumnus": alumnus})

apiweb/apps/interviews/views.py
from django import template
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render

from .models import Post

# from models import Category

register = template.Library()


@login_required
def index(request, category=None):
    posts = Post.objects.filter(is_published=True)

    return render(request, "interviews/index.html", {"posts": posts})


@login_required
def detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    return render(request, "interviews/details.html", {"post": post})

apiweb/templates/footer.html
{% load static %}

<div id="footercontainer">
    <footer class="col-xs-12" id="footer" >
        <div class="footer-row">
            <div class="col-md-3 footer-column hidden-xs hidden-sm">
                <ul style="padding-top:20px;">
                    <a class="twitter-timeline" data-width="300" data-height="300"
                       data-theme="light" href="https://twitter.com/UvA_API">
                        Tweets by @UvA_API</a>
                    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
                </ul>
            </div>

            {% if latest_interviews %}
            <div class="col-xs-12 col-sm-6 col-md-3 footer-column text-centered-xs-sm">
                <h3> Interviews </h3>
                <ul>
                {% if request.user.is_authenticated %}
                    {% for interview in latest_interviews %}
                    <li><a href="{% url 'interviews:detail' interview.slug %}"> {{ interview.alumnus.full_name }} {{ interview.title }} <span>| {{ interview.date_published|date }}</span></a></li>
                    {% endfor %}
                {% else %}
                <li><a href="{% url 'site_login' %}">Please login to view this content.</a></li>
                {% endif %}
                </ul>
            </div>
            {% endif %}

            {% if latest_interviews %}
            <div class="col-xs-12 col-sm-6 col-md-3 footer-column text-centered-xs-sm">
            {% else %}
            <div class="col-xs-12 col-sm-12 col-md-6 footer-column text-centered-xs-sm">
            {% endif %}
                <h3> Recent Theses </h3>
                <ul>
                {% if request.user.is_authenticated %}
                    {% for thesis in latest_theses %}
                    <li><a href=" {% url 'research:thesis-detail' thesis.slug %} "> {{ thesis.alumnus.full_name }}  <span>| {{ thesis.date_of_defence|date }}</span> </a></li>
                    {% endfor %}
                {% else %}
                    <li><a href="{% url 'site_login' %}">Please login to view this content.</a></li>
                {% endif %}
                </ul>
            </div>

            <div class="col-xs-12 visible-xs visible-sm">
                <hr style="border-color: #BAC1C8" />
            </div>

            <div class="col-xs-12 col-md-3 footer-column">
                <div class="row">
                    <div class="col-xs-12" id="contact-wrapper">
                        <img src="{% static 'img/api_logo_default_black.png' %}" title="Anton Pannekoek Institute for Astronomy">

                        <p class="contactinfo">
                            <i class="fa fa-fw fa-home"></i> {{ contactinfo.postbox_address_api }}<br>
                            <i class="fa fa-fw fa-phone"></i> <a href="tel:{{ contactinfo.telephone_api }}">{{ api_phonenumber_formatted }}</a><br>
                            <i class="fa fa-fw fa-envelope"></i> <a href="mailto:{{ contactinfo.secretary_email_address}}">{{ contactinfo.secretary_email_address}}</a><br><br>
                            <i class="fa fa-fw fa-github"></i><a href="https://github.com/tlrh314/UvA_API_Alumni">Open Source</a><br><br>
                            {# <a href="{% url 'contact' %}">Contact Form</a><br> #}


                            {% if request.user.is_authenticated %} <a href="{% url 'login_success' %}">Login</a> {% else %}<a href="{% url 'site_login' %}">Login</a>{% endif %} | <a href="{% url 'login' %}">Admin</a><br>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 visible-xs visible-sm">
                        <hr style="border-color: #BAC1C8" />
                    </div>
                </div>
            </div>

        <div class="col-xs-12" style="text-align: center; width= 100%;">
            <ul class="social">
                    <strong> Stay Connected: </strong><br>
                    <li><a href="https://www.facebook.com/uva.api/" target="_blank"><i
                            class=" fa fa-fw fa-facebook"></i></a></li>
                    <li><a href="https://twitter.com/UvA_API" target="_blank"> <i class="fa fa-fw fa-twitter"></i> </a></li>
                    {# TODO TODO TODO add the API LinkedIn #}
                    <li><a href="https://www.linkedin.com/groups/12005398" target="_blank"> <i class="fa fa-fw fa-linkedin"></i> </a></li>

                </ul>
            <p>&copy; Anton Pannekoek Institute, 2017-2021. All rights reserved.</p>
        </div>
        </div>
    </footer>
</div>

apiweb/templates/header.html
{% load static %}


<header>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand apiLogo" href="{% url 'index' %}">
                <img src="{% static 'img/api_logo_wide_black_alumni.png' %}"/>
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">


            <form class="navbar-form navbar-right" role="search" action="/search/" method="get" accept-charset="utf-8">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." name="terms" id="terms">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <div id="navbar-list-wrapper">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span>ACCOUNT</span></a>
                            <ul class="dropdown-menu navbar-dropdown-wrapper col-xs-12">
                                {% if user.is_superuser %}
                                <li><a href="{% url 'login' %}"><span>ADMIN</span></a></li>
                                <li role="separator" class="divider"></li>
                                {% endif %}
                                <li><a href="{% url 'alumni:alumnus-detail' user.slug %}"><span>MY PROFILE</span></a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'site_password_change' %}"><span>CHANGE PASSWORD</span></a></li>
                                <li><a href="{% url 'site_contactinfo' %}"><span>UPDATE CONTACTINFO</span></a></li>
                                <li><a href="{% url 'site_thesis_select' %}"><span>UPDATE THESES</span></a></li>
                                <li><a href="{% url 'site_careerinfo' 0 %}"><span>UPDATE CURRENT POSITION</span></a></li>
                                <li><a href="{% url 'site_careerinfo' 1 %}"><span>UPDATE FIRST JOB</span></a></li>
                                <li><a href="{% url 'site_careerinfo' 2 %}"><span>UPDATE SECOND JOB</span></a></li>
                                <li><a href="{% url 'site_careerinfo' 3 %}"><span>UPDATE THIRD JOB</span></a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'site_logout' %}"><span>LOGOUT</span></a></li>
                            </ul>
                    </li>
                    <li class="hidden-xs hidden-sm hidden-md"><a>|</a></li>
                    {% else %}
                    <li><a href="{% url 'site_login' %}"><span>LOGIN</span></a></li>
                    <li class="hidden-xs hidden-sm hidden-md"><a>|</a></li>
                    {% endif %}
                    <li><a href="{% url 'alumni:alumnus-list' %}"><span>ALUMNI</span></a></li>
                    <li class="hidden-xs hidden-sm hidden-md"><a>|</a></li>
                    <li><a href="{% url 'research:thesis-list' %}"><span>THESES</span></a></li>
                    {% if latest_interviews %}
                    <li class="hidden-xs hidden-sm hidden-md"><a>|</a></li>
                    <li><a href="{% url 'interviews:index' %}"><span>INTERVIEWS</span></a></li>
                    {% endif %}
                    {% comment %}
                    <li class="hidden-xs hidden-sm hidden-md"><a>|</a></li>
                    <li><a href="{% url 'contact' %}"><span>CONTACT</span></a></li>
                    {% endcomment %}
                    {% if request.user.is_authenticated %}
                    <li class="hidden-xs hidden-sm hidden-md"><a>|</a></li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span>VISUALIZATIONS</span></a>
                        <ul class="dropdown-menu navbar-dropdown-wrapper col-xs-12">
                            <li><a href="{% url 'visualization:tree' %}"><span>STUDENT-SUPERVISOR TREE</span></a></li>
                            <li><a href="{% url 'visualization:view_a' %}"><span>IN ASTRONOMY</span></a></li>
                            <li><a href="{% url 'visualization:view_b' %}"><span>JOB LOCATION</span></a></li>
                            <li><a href="{% url 'visualization:view_d' %}"><span>JOB SECTOR</span></a></li>
                            <li><a href="{% url 'visualization:view_e' %}"><span>LAND OF ORIGIN</span></a></li>
                            <li><a href="{% url 'visualization:view_f' %}"><span>GENDER DISTRIBUTIONS</span></a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>
</header>